"""Canonical Morning Star runtime enumerations."""

from __future__ import annotations

from enum import StrEnum


class ValidationStatus(StrEnum):
    NOT_VALIDATED = "NOT_VALIDATED"
    VALID = "VALID"
    INVALID = "INVALID"
    UNRESOLVED = "UNRESOLVED"


class ObjectStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    PROVISIONAL = "PROVISIONAL"
    SUPERSEDED = "SUPERSEDED"
    REVOKED = "REVOKED"
    ARCHIVED = "ARCHIVED"
    UNRESOLVED = "UNRESOLVED"


class UncertaintyType(StrEnum):
    NONE = "NONE"
    SOURCE = "SOURCE_UNCERTAINTY"
    TRANSLATION = "TRANSLATION_UNCERTAINTY"
    CONTEXTUAL = "CONTEXTUAL_UNCERTAINTY"
    DEPENDENCY = "DEPENDENCY_UNCERTAINTY"
    EVIDENTIARY = "EVIDENTIARY_UNCERTAINTY"
    EQUIVALENCE = "EQUIVALENCE_UNCERTAINTY"
    AUTHORITY = "AUTHORITY_UNCERTAINTY"
    TEMPORAL = "TEMPORAL_UNCERTAINTY"
    IMPLEMENTATION = "IMPLEMENTATION_UNCERTAINTY"


class InterpretationClass(StrEnum):
    CANONICAL = "CANONICAL"
    LITERAL = "LITERAL"
    CONTEXTUAL = "CONTEXTUAL"
    DERIVED = "DERIVED"
    COMPARATIVE = "COMPARATIVE"
    ANALOGICAL = "ANALOGICAL"
    OPERATIONAL = "OPERATIONAL"
    EDUCATIONAL = "EDUCATIONAL"
    TRANSLATIONAL = "TRANSLATIONAL"
    SPECULATIVE = "SPECULATIVE"
    CRITICAL = "CRITICAL"
    CONFLICTING = "CONFLICTING"
    RECONSTRUCTED = "RECONSTRUCTED"
    UNRESOLVED = "UNRESOLVED"
    INADMISSIBLE = "INADMISSIBLE"


class AdmissionStatus(StrEnum):
    ADMISSIBLE = "ADMISSIBLE"
    ADMISSIBLE_WITH_LIMITS = "ADMISSIBLE_WITH_LIMITS"
    ADMISSIBLE_WITH_UNCERTAINTY = "ADMISSIBLE_WITH_UNCERTAINTY"
    PROVISIONAL = "PROVISIONAL"
    CONFLICTING = "CONFLICTING"
    RECONSTRUCTION_REQUIRED = "RECONSTRUCTION_REQUIRED"
    UNRESOLVED = "UNRESOLVED"
    INADMISSIBLE = "INADMISSIBLE"
    SUPERSEDED = "SUPERSEDED"


class ParticipationRole(StrEnum):
    PR0 = "PR0"
    PR1 = "PR1"
    PR2 = "PR2"
    PR3 = "PR3"
    PR4 = "PR4"
    PR5 = "PR5"
    PR6 = "PR6"


class InitiationDecision(StrEnum):
    ADMIT = "ADMIT"
    ADMIT_WITH_LIMITS = "ADMIT_WITH_LIMITS"
    ADMIT_PROVISIONALLY = "ADMIT_PROVISIONALLY"
    DEFER = "DEFER"
    REQUIRE_REMEDIATION = "REQUIRE_REMEDIATION"
    REQUIRE_REASSESSMENT = "REQUIRE_REASSESSMENT"
    DENY = "DENY"
    SUSPEND = "SUSPEND"
    REVOKE = "REVOKE"
    RENEW = "RENEW"
    EXPIRE = "EXPIRE"


class ConstitutionalState(StrEnum):
    UNENCOUNTERED = "MS-S0"
    ENCOUNTERED = "MS-S1"
    IDENTIFIED = "MS-S2"
    CONTEXTUALIZED = "MS-S3"
    DEPENDENCY_RESOLVED = "MS-S4"
    INTERPRETED = "MS-S5"
    COMPETENCY_EVALUATED = "MS-S6"
    PARTICIPATION_ADMITTED = "MS-S7"
    PARTICIPATION_ACTIVE = "MS-S8"
    REVALIDATION_REQUIRED = "MS-S9"
    RECONSTRUCTION_REQUIRED = "MS-S10"
    SUSPENDED = "MS-S11"
    REVOKED = "MS-S12"
    EXITED = "MS-S13"
